# podman build -t opensearch:fbOS -f Buildfile
# podman run --rm --name fbOS opensearch:fbOS
FROM ghcr.io/fluent/fluent-bit:4.2.0

COPY ./fluent-bit.yaml /fluent-bit/etc/fluent-bit.yaml

ENTRYPOINT [ "fluent-bit" ]
CMD [ "-c", "/fluent-bit/etc/fluent-bit.yaml"]